spring.application.name=biorevive

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/biorevive_db
spring.datasource.username=postgres
spring.datasource.password=Anway1234

# Hibernate & JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect